### PR TITLE
Add support for per-edge ideal length.

### PR DESCRIPTION
**Pull request by bradh**
This allows a function to override the ideal edge length based on edge properties. 

I have a case where I'd really like to keep some edges very short (to indicate particular node-to-node relationships). A function seems like a reasonably generic approach.

### CODE REVIEW

**Comment by maxkfranz** [comment]
I would prefer to use only the existing option, `idealEdgeLength`, and allow it to take on either an integer value or a function value.  All the code could be changed to assume it's always a function, except the init code: If the init value is an int, then make a function from it, e.g. `idealEdgeLength = edge => idealEdgeLengthInt`.

**Comment by DukeBaird** [comment]
One of the things that doesn't work for me is that I can't access the edge data from the edge that is passed into the function.

With the COSE layout, I can get `edge.data().foo`, but this passes in an edge that doesn't have these properties.

**Comment by maxkfranz** [comment]
So then maybe my function-all-the-time idea is probably too strict.  The value could be cached as a plain int at some point in the layout code.  The main thing I wanted to get across is that the public API should be simple, using the same property.

**Comment by DukeBaird** [comment]
Sorry Max, I meant with the code in the PR. Having it as a function all the time is fine (with my case), as long as that edge is the same as is in the other layout.

My function is:
```
idealEdgeLength: function(edge) {
 	return edge.data().weight; // weight is edge-dependent
 },
```

I agree that it would be nice if it were the same property, whether its a static int, or a function.

**Comment by maxkfranz** [comment]
I think the layout makes its own element objects though, so it won't necessarily have access to the original `data()` or `ele` if `idealEdgeLength` uses a function everywhere.

**Comment by DukeBaird** [comment]
Oh I see. Guess I'm stuck with COSE either way then. Thanks for pointing that out before I got super stuck and frustrated.

**Comment by maxkfranz** [comment]
Both default COSE and Cola should support function edge lengths already.  Both Cola and COSE-Bilkent tend to produce nicer results than default COSE, but default COSE is relatively inexpensive.  It would be great to have function support in COSE-Bilkent directly though, as it by far produces the best results for compound graphs.

**Comment by bradh** [comment]
I originally started with just allowing `idealEdgeLength` to be a function or a constant, but there are two problems:

- the option value gets assigned to a constant (in FDConstants and CoSEConstants) which is arguably public API, 
- the constants get used in other places, including places where we don't easily have an edge to work with (e.g. the circular node layout). I don't want to do that much refactoring, nor do I have confidence I understand all the consequences of such a change.

Those two things led me to adding an option.

**Comment by bradh** [comment]
I had a look at how hard it would be to add `data()`, and it turns out it will be somewhat messy. 

Two options I came up with. First is to use the `edge.id` (which is already present) to do an element lookup. So you can set some property on the edge data (e.g. `"myEdgeLength": "90"`) and then do something like this in the per-edge length function:
```
idealEdgeLengthFunction: function(edge) {
              if (edge.source.id === 'glyph33') {
                return 100;
              } else if (edge.id) {
                var el = cy.getElementById(edge.id);
                var data = el.data();
                if (data) {
                  var len = data.myTargetLength;
                  if (len) {
                    return len;
                  }
                }
                return 50;
              } else {
                return 50;
              }
```

If it turns out its an expensive lookup, you could cache them by `edge.id`, although I admit its now getting complicated.

The second alternative is to copy off `data()` in the LEdge constructor, and add an event listener to keep it up to date when the edge data changes. Unfortunately I couldn't find a cytoscape.js event that is per-edge, so I just update them all when the collection raises the `data` event.
The change looks like:
```
--- a/src/Layout/index.js
+++ b/src/Layout/index.js
@@ -167,6 +167,7 @@ _CoSELayout.prototype.run = function () {
     if(sourceNode.getEdgesBetween(targetNode).length == 0){
       var e1 = gm.add(layout.newEdge(), sourceNode, targetNode);
       e1.id = edge.id();
+      e1.setData(edge.data());
     }
   }
   
@@ -233,6 +234,14 @@ _CoSELayout.prototype.run = function () {
         cancelAnimationFrame(frameId);
       }
       
+      this.cy.eles().addEventListener('data', function() {
+        var gmedges = gm.edges;
+        for (var e = 0; e < gmedges.length; e++) {
+          var cyEdge = this.cy.getElementById(e.id);
+          e.setData(cyEdge.data());
+        }
+      });
+
       ready = false;
       return;
     }
```
(with a corresponding change to add the getter / setter in LEdge.js).

Then you can do something like:
```
idealEdgeLengthFunction: function(edge) {
              if (edge.source.id === 'glyph33') {
                return 100;
              } else if (edge.data() && edge.data().myTargetLength) {
                return edge.data().myTargetLength;
              } else {
                return 50;
              }
            }
```

Obviously a real application is probably doing some calculations / switch based on actual data, rather than a constant, but you get the idea.

**Comment by DukeBaird** [comment]
That works super well with the small data sets I'm using, so I'm pretty happy. Once some other people show up tonight I can see how it will perform with a much larger one.

**Comment by maxkfranz** [comment]
I think the simplest thing would be to store the per-element values in COSEEdge and COSENode, set in their constructors.  Every place in the code that uses the constants, for things like ideal edge length, would have to read from the element rather than the global constants.

I don't think the values need to be updated once the layout has started.  IIRC, other FD layouts don't do that.  Overall to change layout params, you stop the running layout and start a new one.  That has the same effect.

**Comment by maxkfranz** [comment]
Also: I don't think sending just `data` is as general as it could be.  It's best to run directly on the Cytoscape element, like `someForce(ele)` so you can call things like `ele.degree()` inside `someForce()`.  Using the full model object is also more consistent with other layouts.

**Comment by DavidDecraene** [comment]
Was there a specific reason why this didn't get integrated into the master?

I was hoping to be able to specify ideal edge length per edge, but can't seem to do that in version "cytoscape-cose-bilkent": "4.1.0"

**Comment by bradh** [comment]
I closed it because it wasn't going to be accepted and I didn't have time to work it. Feel free to rework it as required.

**Comment by ugurdogrusoz** [comment]
There are 2 major concerns about per edge ideal length specification:
- Fine tuning: spring embedders are difficult to tune. When you change the ideal edge length, repulsion and spring forces no longer balance each other out and you get layouts far from ideal
- Performance: as is, this is not a very fast layout, it will get slower with this

So I am for not making such a change.

**Pull request closed without merging**
