### PR TITLE
Port to updated scaffolding

### PR DESCRIPTION
**Pull request by maxkfranz**
This brings this extension up-to-date with the latest scaffolding.  It fixes some issues with your build system, and it provides some general benefits.

- Allows for automatically posting demos to gh-pages when publishing.
- Allows for specifying external dependencies with webpack umd definition.  Fixes issue with referencing `linkedlist-js` in prod builds.
- Source unchanged.
- Updates Babel to env preset (i.e. support for post-es2015).
- Publishing steps are a bit different.  Refer to readme.
- Demos on the main Cytoscape.js docs site can now use the demos you define in this repo.  They will automatically be kept up-to-date!

N.b. this requires publishing a new major version, as we don't want to support versions before cytoscape@3.1.0 anymore in this extension. I've updated the ref to 3.2.0 to be more conservative.

### CODE REVIEW

**Comment by maxkfranz** [comment]
This requires publishing a new major version, as we don't want to support versions before cytoscape@3.1.0 anymore.

**Comment by hasanbalci** [comment]
@maxkfranz I reverted it because I think there is a problem with build. Can you verify whether the build works correctly or I couldn't manage to it.

**Comment by maxkfranz** [comment]
Merge #67

Explanation: If you want to use external dependencies properly, you can't embed them in the bundle.  A debug/watch build will bundle things for you so you can test with specific dependency versions etc., but a prod build should not.  Note that if you run a watch, you can use the demo just fine before your reversion.  But you should never use a watch build as a dist/prod file or for public demos.

Unfortunately, your choice of linked list lib is not good if you want to have an easily supported public demo.  It does not support globals, so you can't use an unpkg or cdnjs script tag for it.

This means to support demos, you need to do one of:

(1) Use a different lib that supports globals, like [`linked-list`](https://www.npmjs.com/package/linked-list) -- ~100,000 downloads per month versus ~100 for [`linkedlist-js`](https://www.npmjs.com/package/linkedlist-js).

(2) Make separate builds per demo, as each demo is a small app.  More complicated and expensive to maintain.  Less readable as example code for users.

(3) Just use an Array instead of a linked list.  You're using it like a queue (which an Array is) anyway.  This is the simplest option and what #67 does.

**Comment by hasanbalci** [comment]
@maxkfranz The array version slows down the algorithm too much, that's why we wanted to switch to a linked list implementation. I will try the library you suggested in (1) before merging #67. Thanks.

**Comment by maxkfranz** [comment]
If performance is that much of a concern, you're probably better off just implementing your own linked list.  You could copy the Java API if you want the code to be like your Java package: https://docs.oracle.com/javase/9/docs/api/java/util/LinkedList.html

**Comment by maxkfranz** [comment]
@hasanbalci @ugurdogrusoz I added a LinkedList class that is interface-compatible with the Array queueing functions: https://github.com/cytoscape/cytoscape.js-cose-bilkent/pull/67/commits/2715a3f86c337f121f72d0270a9c7bad4850deb2

 You can just swap the visited list implementation back and forth to test performance: https://github.com/cytoscape/cytoscape.js-cose-bilkent/pull/67/commits/a158455a6cb1ef477251861e0057754e2af0c068

**Pull request merged**
