### PR TITLE
move dummy_parent_id to scratch

### PR DESCRIPTION
**Pull request by bastiion**
I use several layout algorithms in  a project, where the user can choose out of a list of layouts. For the case-bilkent layout I recognized an added property in the data section of nodes called `dummy_parent_id` and sometimes `tempchildren`.
This messes up the data-editor as my app assumes that only clean data is stored there. Cytoscape.JS has a `scratch`-store for such things, that to my opinion is much more suitable in this particular case.
I made some small modifications in order to store the data in `scratch` instead of `data`.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@bastiion Great!  Scratchpad data is definitely the right approach.  One small thing though: The scratch data should be namespaced, e.g. `ele.scratch('coseBilkent') = {} ...`  Otherwise, you can collide with other extensions.

**Comment by bastiion** [comment]
@maxkfranz would it be sufficient to prefix the namespace like `coseBilkent_dummy_parent_id` and `coseBilkent_temp_children`?

**Comment by maxkfranz** [comment]
It's safer to use a separate object, because that's what's encouraged in the documentation.  Each extension is supposed to be able to assume it can use it's camelcase name for an object, and there are no guarantees of collision avoidance otherwise.

**Comment by metincansiper** [comment]
@bastiion thanks for your contribution. I have relased '1.3.8' after merging this PR.

**Pull request merged**
